spring:
  profiles: test

eureka:
  client:
    serviceUrl:
      defaultZone: http://test-eureka:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true