spring:
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      prefer-ip-address: true
    client:
      register-with-eureka: true
      fetch-registry: true