spring:
  profiles: dev

#datasource
datasource.ip_port: localhost:3306
datasource.username: root
datasource.password: root1234

aop.auto: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      prefer-ip-address: true
    client:
      register-with-eureka: true
      fetch-registry: true