spring:
  profiles: test

#datasource
datasource.ip_port: localhost:3306
datasource.username: root
datasource.password: root1234

#rabbitmq
rabbitmq.host: localhost
rabbitmq.port: 5672
rabbitmq.username: guest
rabbitmq.password: guest

aop.auto: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://test-eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true